server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://prod-mysql:3306/auth_bd?useSSL=true&serverTimezone=UTC
    username: auth_user          # ❗ replace per environment
    password: auth_password      # ❗ replace per environment
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate         # ❗ NEVER use update in prod
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

jwt:
  secret: prod_jwt_secret_change_later   # ❗ move to Vault later
  access-token-expiration: 900000        # 15 minutes
  refresh-token-expiration: 604800000    # 7 days
  issuer: auth-service
  audience: consulting-app

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    com.consulting: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: OFF
